In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df=pd.read_csv("../datasets/CarSpeedData..csv")

In [3]:
df.rename(columns={"Unnamed: 1":"Speed"},inplace=True)

In [10]:
df

    Gender  Speed Average_speed     City has_driving_license  Age
0     male   40.0           low  Kolkata                 yes   54
1   female   70.0           low    Delhi                 yes   34
2   female  140.0          high   Delhi                   no   19
3     male  120.0          high  Kolkata                 yes   45
4    male    80.0           low   Mumbai                  no   23
..     ...    ...           ...      ...                 ...  ...
95  female   50.0           low    Delhi                  no   21
96    male   70.0           low   Mumbai                 yes   29
97  female   50.0           low   Mumbai                  no   40
98  female   50.0           low  Kolkata                 yes   42
99    male   60.0           low  Kolkata                  no   20

[100 rows x 6 columns]

In [5]:
df.isnull().sum()

Gender                 0
Speed                  9
Average_speed          0
City                   0
has_driving_license    0
Age                    0
dtype: int64

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.drop("has_driving_license",axis='columns'),df["has_driving_license"],test_size=0.2)
x_train.shape,x_test.shape

((80, 5), (20, 5))

In [7]:
from sklearn.compose import ColumnTransformer
transformer= ColumnTransformer(transformers=[
    ('t1',SimpleImputer(),["Speed"]),
    ('t2',OneHotEncoder(sparse_output=False,drop="first"),["Gender","City"]),
    ('t3',OrdinalEncoder(categories=[['low','high']]),['Average_speed'])
],remainder='passthrough')

In [8]:
transformer.fit_transform(x_train).shape
transformer.transform(x_test).shape

(20, 10)

In [9]:
x_train

    Gender  Speed Average_speed      City  Age
89    male   90.0           low    Mumbai   45
15  female  120.0          high   Kolkata   47
91  female  170.0          high  Banglore   36
29  female   40.0           low   Kolkata   36
65  female  170.0          high   Kolkata   37
..     ...    ...           ...       ...  ...
12    male  170.0          high   Kolkata   61
56  female   50.0           low     Delhi   39
33  female   50.0           low  Banglore   35
59    male   40.0           low  Banglore   32
92    male   60.0           low    Mumbai   37

[80 rows x 5 columns]