In [2]:
import numpy as np 
import pandas as pd

In [3]:
df=pd.read_csv("../datasets/Used_Bikes.csv")

In [4]:
df.head(10)

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
5,Yamaha FZs 150cc,53499.0,Delhi,25000.0,First Owner,6.0,150.0,Yamaha
6,Honda CB Hornet 160R ABS DLX,85000.0,Delhi,8200.0,First Owner,3.0,160.0,Honda
7,Hero Splendor Plus Self Alloy 100cc,45000.0,Delhi,12645.0,First Owner,3.0,100.0,Hero
8,Royal Enfield Thunderbird X 350cc,145000.0,Bangalore,9190.0,First Owner,3.0,350.0,Royal Enfield
9,Royal Enfield Classic Desert Storm 500cc,88000.0,Delhi,19000.0,Second Owner,7.0,500.0,Royal Enfield

In [5]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.drop(columns="price"),df["price"],test_size=0.2,random_state=0)

In [6]:
x_train

,bike_name,city,kms_driven,owner,age,power,brand
15296,Hero Passion Pro 100cc,Delhi,22000.0,First Owner,4.0,100.0,Hero
15180,Bajaj Avenger 220cc,Delhi,20245.0,Second Owner,11.0,220.0,Bajaj
11583,Bajaj Pulsar NS200,Allahabad,41939.0,First Owner,8.0,200.0,Bajaj
20838,Bajaj Pulsar 150cc,Delhi,32588.0,First Owner,9.0,150.0,Bajaj
6083,Hero Passion Pro 100cc,Ludhiana,12000.0,First Owner,9.0,100.0,Hero
...,...,...,...,...,...,...,...
13123,KTM RC 390cc,Mumbai,13216.0,First Owner,4.0,390.0,KTM
19648,Bajaj Avenger 220cc,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9845,Bajaj Avenger Street 220,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
10799,Suzuki Slingshot Plus 125cc,Lucknow,22697.0,First Owner,7.0,125.0,Suzuki
2732,Suzuki Intruder 150cc FI,Kollam,14495.0,First Owner,3.0,150.0,Suzuki

In [34]:
x_train_new=x_train["brand"]
x_train_new=pd.DataFrame(x_train_new,columns=["brand"])
x_test_new=x_test["brand"]
x_test_new=pd.DataFrame(x_test_new,columns=["brand"])

In [35]:
x_train_new

        brand
15296    Hero
15180   Bajaj
11583   Bajaj
20838   Bajaj
6083     Hero
...       ...
13123     KTM
19648   Bajaj
9845    Bajaj
10799  Suzuki
2732   Suzuki

[26118 rows x 1 columns]

In [48]:
counts = x_train_new["brand"].value_counts()

frequent = counts[counts >= 100].index

x_train_new["brand_processed"] = x_train_new["brand"].where(
    x_train_new["brand"].isin(frequent),
    "uncommon"
)

x_train_new.sample(10)

        brand brand_processed
8037    Honda           Honda
27646   Bajaj           Bajaj
19298     KTM             KTM
10103    Hero            Hero
17884   Bajaj           Bajaj
27086    Hero            Hero
28443    Hero            Hero
17423    Hero            Hero
23322   Bajaj           Bajaj
2745   Yamaha          Yamaha

In [27]:
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder(drop="first",sparse_output=False)
x_train_new=ohe.fit_transform(x_train_new)

In [28]:
x_train_new

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 26118 stored elements and shape (26118, 22)>