In [1]:
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
df=pd.read_csv("../datasets/customer.csv")

In [3]:
df.sample(10
         )

    age  gender   review education purchased
42   30  Female     Good        PG       Yes
34   86    Male  Average    School        No
49   25  Female     Good        UG        No
12   51    Male     Poor    School        No
0    30  Female  Average    School        No
22   18  Female     Poor        PG       Yes
48   39  Female     Good        UG       Yes
45   61    Male     Poor        PG       Yes
27   69  Female     Poor        PG        No
29   83  Female  Average        UG       Yes

In [4]:
df["review"].unique()

array(['Average', 'Poor', 'Good'], dtype=object)

In [5]:
df=df.iloc[:,2:]

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.iloc[:,:2],df["purchased"],test_size=0.2,random_state=0)

In [7]:
x_train.shape , x_test.shape

((40, 2), (10, 2))

In [22]:
x_train.head()

     review education
33     Good        PG
35     Poor    School
26     Poor        PG
34  Average    School
18     Good    School

In [9]:
from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder(categories=[["Poor","Average","Good"],["School","UG","PG"]])
oe.fit(x_train)
x_train_oe=oe.transform(x_train)
x_test_oe=oe.transform(x_test)

In [18]:
x_train_oe=pd.DataFrame(x_train_oe,columns=x_train.columns)

In [19]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
le.fit(y_train)
y_train_le=le.transform(y_train)
y_test_le=le.transform(y_test)

In [23]:
y_train_le

array([1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0])